/**
 * Phase 1 runner for dependency-cruiser: circular imports and orphan modules.
 *
 * Only two things are read out of the cruise: the rings behind `cycle`
 * violations and the modules the graph marks as orphans. Whatever else a
 * target's own ruleset forbids is its business, not a Sentinel finding.
 *
 * The analysed repository is never written to: when it has no configuration of
 * its own, a minimal ruleset is generated in the run directory and passed with
 * `--config`.
 */

import { join, resolve } from "node:path";
import type { Finding } from "../../contracts/findings.ts";
import { isMonorepo, workspacePackages } from "../../profile/index.ts";
import {
  type DependencyCycle,
  cyclesOf,
  detectsCycles,
  detectsOrphans,
  orphansOf,
  parseDependencyCruiserReport,
} from "../parsers/dependency-cruiser.ts";
import type { StepOutcome, StepStatus } from "../types.ts";
import {
  type RunnerContext,
  briefly,
  failedStep,
  joinReasons,
  makeFinding,
  outcome,
  skipped,
  verifyStepFindings,
  writeRaw,
} from "./_runner-support.ts";

/** Step name, matching the tool it drives. */
export const DEPENDENCY_CRUISER_STEP = "dependency-cruiser";

/** Lockfile name in `tools.lock.json`; the resolver maps it to the pinned binary. */
export const DEPENDENCY_CRUISER_TOOL = "dependency-cruiser";

/** Cruising a large graph is slower than linting a file; budget accordingly. */
export const DEPENDENCY_CRUISER_DEFAULT_TIMEOUT_MS = 300_000;

/** Name of the ruleset Sentinel generates in the run dir when the target has none. */
export const GENERATED_CONFIG_NAME = "dependency-cruiser.config.mjs";

/** Configuration file names dependency-cruiser looks for in a repository. */
const TARGET_CONFIG_NAMES: readonly string[] = [
  ".dependency-cruiser.json",
  ".dependency-cruiser.js",
  ".dependency-cruiser.cjs",
  ".dependency-cruiser.mjs",
  ".dependency-cruiser.config.js",
  ".dependency-cruiser.config.cjs",
  ".dependency-cruiser.config.mjs",
];

/** Directories worth cruising when the profile does not name any. */
const SOURCE_DIR_CANDIDATES: readonly string[] = [
  "src",
  "app",
  "lib",
  "server",
  "pages",
  "api",
  "source",
  "apps",
  "packages",
];

/** Paths that are orphans by design and would only add noise. */
const ORPHAN_EXCLUSIONS: readonly string[] = [
  "[.]d[.]ts$",
  "(^|/)[.][^/]+$",
  "[.]config[.][cm]?[jt]sx?$",
  "(^|/)(vite|vitest|jest|rollup|webpack|next|tailwind|postcss|babel|eslint|knip|biome)[.]",
];

/** Directories that are build output rather than source. */
const EXCLUDED_PATHS: readonly string[] = [
  "node_modules",
  "(^|/)(dist|build|out|coverage|[.]next|[.]turbo|[.]output)/",
];

/**
 * The minimal ruleset Sentinel cruises with when the target has none of its
 * own. Serialised from a plain object so the generated file cannot go wrong on
 * an escaped character.
 */
export function generatedConfig(tsConfigFile: string | null): string {
  const config = {
    forbidden: [
      { name: "no-circular", severity: "warn", from: {}, to: { circular: true } },
      {
        name: "no-orphans",
        severity: "warn",
        from: { orphan: true, pathNot: ORPHAN_EXCLUSIONS },
        to: {},
      },
    ],
    options: {
      doNotFollow: { path: ["node_modules"] },
      exclude: { path: EXCLUDED_PATHS },
      combinedDependencies: true,
      ...(tsConfigFile === null ? {} : { tsConfig: { fileName: tsConfigFile } }),
    },
  };
  return [
    "// AUTO-GENERATED by Sentinel phase 1 - DO NOT EDIT.",
    "// Written to the run directory so the analysed repository is never modified.",
    `export default ${JSON.stringify(config, null, 2)};`,
    "",
  ].join("\n");
}

/** The target's own configuration path, or null when it has none. */
async function findTargetConfig(ctx: RunnerContext): Promise<string | null> {
  for (const name of TARGET_CONFIG_NAMES) {
    const candidate = join(ctx.targetDir, name);
    if (await ctx.fs.exists(candidate)) return candidate;
  }
  return null;
}

/** The directories to cruise: workspace packages when known, common roots otherwise. */
export async function sourceDirs(ctx: RunnerContext): Promise<string[]> {
  const candidates: string[] = [];
  const profile = ctx.profile;
  if (profile !== undefined && isMonorepo(profile)) {
    candidates.push(...workspacePackages(profile));
  }
  candidates.push(...SOURCE_DIR_CANDIDATES);

  const found: string[] = [];
  for (const candidate of candidates) {
    if (candidate === "" || candidate === ".") continue;
    if (found.includes(candidate)) continue;
    if (await ctx.fs.exists(join(ctx.targetDir, candidate))) found.push(candidate);
  }
  // Nothing recognisable: cruise the repository root and let the exclusions work.
  return found.length === 0 ? ["."] : found;
}

/**
 * A directory holding a `typescript` package, so dependency-cruiser can parse
 * `.ts` sources at all — without one it silently cruises only JavaScript.
 * Sentinel's own copy is preferred: it is a known version and, unlike the
 * target's, it is not code from the repository under audit.
 */
async function typescriptNodePath(ctx: RunnerContext): Promise<string | null> {
  const sentinelModules = resolve(import.meta.dir, "..", "..", "..", "node_modules");
  for (const candidate of [sentinelModules, join(ctx.targetDir, "node_modules")]) {
    if (await ctx.fs.exists(join(candidate, "typescript", "package.json"))) return candidate;
  }
  return null;
}

/** Turns one canonical ring into a finding that cites every module in it. */
export function cycleFinding(cycle: DependencyCycle): Finding {
  const head = cycle.modules[0] ?? "";
  return makeFinding({
    domain: "deadcode",
    rule: "deadcode.circular-dependency",
    severity: "low",
    confidence: "high",
    title: `Circular import: ${briefly(cycle.key, 120)}`,
    description: `dependency-cruiser resolved this import ring: ${cycle.key}. Every module in the ring is partially initialised while the others are still loading, so which one wins depends on whichever file the runtime happens to enter first.`,
    impact:
      "Cycles produce order-dependent initialisation bugs that only appear under a different entry point, block tree-shaking, and make each module in the ring impossible to test or reuse on its own.",
    recommendation:
      "Break the ring: move the shared declarations into a module both sides import, or invert one of the dependencies so it points in a single direction.",
    acceptanceCriteria: [
      `No module in \`${cycle.key}\` imports another member of the ring back.`,
      "A fresh cruise reports no cycle containing these modules.",
    ],
    file: head,
    line: 1,
    symbol: cycle.key,
    evidence: cycle.modules
      .slice(1)
      .map((module) => ({ file: module, line: 1, note: "part of the same cycle" })),
    source: { kind: "tool", name: DEPENDENCY_CRUISER_STEP },
  });
}

/** Turns one orphan module into a finding, worded as the candidate it is. */
export function orphanFinding(module: string): Finding {
  return makeFinding({
    domain: "deadcode",
    rule: "deadcode.orphan-module",
    severity: "info",
    confidence: "medium",
    title: `Orphan module candidate: ${module}`,
    description: `\`${module}\` neither imports another cruised module nor is imported by one, so it sits outside the dependency graph entirely. This is a candidate: an entry point, a script, a test helper and a file loaded by framework convention all look identical to dead code from the graph's point of view, which is why phase 5 re-checks it.`,
    impact:
      "A module outside the graph is never exercised by the code paths reviewers read, so it rots quietly and can hide behaviour nobody expects to still be shipping.",
    recommendation:
      "Confirm the file is not an entry point or convention-loaded, then delete it — or wire it into the graph if it should be reachable.",
    acceptanceCriteria: [
      "The file is deleted, or the reason it stays outside the graph is recorded.",
      "The build and the test suite still pass without it.",
    ],
    file: module,
    line: 1,
    symbol: module,
    source: { kind: "tool", name: DEPENDENCY_CRUISER_STEP },
  });
}

/**
 * Cruises the target's module graph and normalises cycles and orphans into
 * findings. Never throws: a missing tool or an empty graph is `skipped`,
 * untrustworthy output is `failed`, and a cruise that could not read TypeScript
 * or ran under a ruleset with no cycle rule is `degraded` with the reason said
 * out loud.
 */
export async function runDependencyCruiser(ctx: RunnerContext): Promise<StepOutcome> {
  const startedAt = performance.now();
  const timeoutMs = ctx.timeoutMs ?? DEPENDENCY_CRUISER_DEFAULT_TIMEOUT_MS;

  if (!(await ctx.fs.exists(join(ctx.targetDir, "package.json")))) {
    return skipped(DEPENDENCY_CRUISER_STEP, startedAt, "the target has no package.json");
  }

  const binary = await ctx.tools.resolve(DEPENDENCY_CRUISER_TOOL, {
    allowPath: ctx.allowPathTools === true,
  });
  if (binary === null) {
    return skipped(
      DEPENDENCY_CRUISER_STEP,
      startedAt,
      "dependency-cruiser is not installed; run `sentinel setup` (circular and orphan modules will not be reported)",
    );
  }

  const notes: (string | null)[] = [];
  const artifacts: string[] = [];

  let configPath = await findTargetConfig(ctx);
  if (configPath === null) {
    const tsConfig = (await ctx.fs.exists(join(ctx.targetDir, "tsconfig.json")))
      ? "tsconfig.json"
      : null;
    configPath = join(ctx.runDir, "raw", DEPENDENCY_CRUISER_STEP, GENERATED_CONFIG_NAME);
    await ctx.fs.writeFile(configPath, generatedConfig(tsConfig));
    artifacts.push(configPath);
  }

  const nodePath = await typescriptNodePath(ctx);
  if (nodePath === null) {
    notes.push(
      "no `typescript` package was available to dependency-cruiser, so TypeScript sources were not parsed and only JavaScript modules were cruised",
    );
  }

  const dirs = await sourceDirs(ctx);
  const args = ["--config", configPath, "--output-type", "json", ...dirs];
  const result = await ctx.exec.run(binary, args, {
    cwd: ctx.targetDir,
    timeoutMs,
    env: { NO_COLOR: "1", ...(nodePath === null ? {} : { NODE_PATH: nodePath }) },
  });

  if (result.stdout !== "") {
    artifacts.push(
      await writeRaw(ctx, DEPENDENCY_CRUISER_STEP, "dependency-cruiser.json", result.stdout),
    );
  }
  if (result.stderr.trim() !== "") {
    artifacts.push(
      await writeRaw(ctx, DEPENDENCY_CRUISER_STEP, "dependency-cruiser.stderr.log", result.stderr),
    );
  }

  if (result.notFound) {
    return skipped(
      DEPENDENCY_CRUISER_STEP,
      startedAt,
      `dependency-cruiser is not executable at ${binary}`,
    );
  }
  if (result.timedOut) {
    return failedStep(
      DEPENDENCY_CRUISER_STEP,
      startedAt,
      `dependency-cruiser timed out after ${timeoutMs} ms`,
      artifacts,
    );
  }
  if (result.truncated) {
    return failedStep(
      DEPENDENCY_CRUISER_STEP,
      startedAt,
      "dependency-cruiser output exceeded the capture limit and was truncated",
      artifacts,
    );
  }

  // A non-zero exit with output is normal: it means the ruleset was violated.
  const stdout = result.stdout.trim();
  if (stdout === "") {
    return failedStep(
      DEPENDENCY_CRUISER_STEP,
      startedAt,
      `dependency-cruiser exited ${result.exitCode} without output: ${briefly(result.stderr, 200) || "no stderr"}`,
      artifacts,
    );
  }

  const report = parseDependencyCruiserReport(stdout);
  if (!report.ok) {
    return failedStep(DEPENDENCY_CRUISER_STEP, startedAt, report.error, artifacts);
  }

  if (report.value.summary.totalCruised === 0) {
    return outcome(
      DEPENDENCY_CRUISER_STEP,
      "skipped",
      joinReasons([`nothing to cruise under ${dirs.join(", ")}`, ...notes]),
      [],
      artifacts,
      startedAt,
    );
  }

  if (!detectsCycles(report.value)) {
    notes.push(
      "the dependency-cruiser configuration that ran has no circular-dependency rule, so cycles were not reported",
    );
  }
  if (!detectsOrphans(report.value)) {
    notes.push(
      "the dependency-cruiser configuration that ran has no orphan rule, so orphan modules were not reported",
    );
  }

  const findings = [
    ...cyclesOf(report.value).map(cycleFinding),
    ...orphansOf(report.value).map(orphanFinding),
  ];
  const verified = await verifyStepFindings(findings, ctx);
  if (verified.droppedFindings > 0) {
    notes.push(
      `${verified.droppedFindings} finding(s) dropped: the module dependency-cruiser named does not resolve to a readable file in the repository`,
    );
  }

  const status: StepStatus = notes.length === 0 ? "ok" : "degraded";
  return outcome(
    DEPENDENCY_CRUISER_STEP,
    status,
    joinReasons(notes),
    verified.kept,
    artifacts,
    startedAt,
  );
}
