FROM node:20.11.0-alpine3.19 AS build
WORKDIR /app
COPY package.json bun.lock ./
RUN npm ci --no-audit && npm cache clean --force
COPY src ./src
RUN npm run build

FROM node:20.11.0-alpine3.19 AS runtime
WORKDIR /app
COPY --from=build /app/dist ./dist
USER node
HEALTHCHECK --interval=30s CMD ["node", "dist/health.js"]
CMD ["node", "dist/index.js"]
